function [media_izquierda,media_derecha]=medias(RGB,se)
Ig=rgb2gray(RGB);
thres=Ig>8;
thres_eroded=imerode(thres,se);
contour=thres-thres_eroded;
[filas, columnas, ~] = size(contour);
mitad_derecha_negra = contour(:, floor(columnas/2) + 1:end, :);
mitad_derecha_negra(:) = 0;
contour_izquierda = cat(2, contour(:, 1:floor(columnas/2), :), mitad_derecha_negra);
mitad_izquierda_negra = contour(:, 1:floor(columnas/2), :);
mitad_izquierda_negra(:) = 0;
contour_derecha = cat(2, mitad_izquierda_negra, contour(:, floor(columnas/2) + 1:end, :));
RGB=double(RGB);
plantilla_izquierda=RGB.*contour_izquierda;
plantilla_izquierda=uint8(plantilla_izquierda);
plantilla_derecha=RGB.*contour_derecha;
plantilla_derecha=uint8(plantilla_derecha);
elementosNoCero_izquierda = nonzeros(plantilla_izquierda);
suma_izquierda = sum(elementosNoCero_izquierda);
media_izquierda = mean(elementosNoCero_izquierda);
elementosNoCero_derecha = nonzeros(plantilla_derecha);
suma_derecha = sum(elementosNoCero_derecha);
media_derecha = mean(elementosNoCero_derecha);
end